--- #YAML:1.0
name:               ACME-YAPC-NA-2012
version:            0.02
abstract:           The great new ACME::YAPC::NA::2012!
author:
    - Jacinta Richardson <jarich@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
